### ISSUE TITLE
Error when converting Raiffeisen CSV

### ISSUE THREAD

**Issue by mjowe** [nblock/ofxstatement-austrian#1]
Hi!

I tried to convert a CSV file from my austrian Giro to OFX. On the website on "Umsätze" I choose "Daten Exportieren" and download it in the CSV format.
ofxstatement throws the following error when converting:
Traceback (most recent call last):
  File "/usr/local/bin/ofxstatement", line 9, in <module>
    load_entry_point('ofxstatement==0.5.0', 'console_scripts', 'ofxstatement')()
  File "/usr/local/lib/python3.4/dist-packages/ofxstatement/tool.py", line 145, in run
    return args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/ofxstatement/tool.py", line 121, in convert
    parser = p.get_parser(args.input)
  File "/usr/local/lib/python3.4/dist-packages/ofxstatement/plugins/raiffeisen.py", line 59, in get_parser
    parser.statement.account_id = self.settings['account']
KeyError: 'account'

Here is a line from the CSV-File to reproduce the problem:
29.06.2015;"AUTOMAT 00970314 K2 27.06.UM 22:44";27.06.2015;-40,00;EUR;28.06.2015 03:17:44:231;

Thanks a lot for your effort!

**Comment by nblock** [comment]
Thank you very much for your report. I was able to reproduce the issue and will try to fix it asap.

**Comment by nblock** [comment]
A new release 0.0.2 is now available which fixes this issue. Alternatively, you may consider to configure an account for raiffeisen using: `ofxstatement edit-config`.

Here is an example config:

```
[raiffeisen]
plugin = raiffeisen
account = 1234567
```
