### ISSUE TITLE
libOFX throws errors when consuming the file

### ISSUE THREAD

**Issue by mjowe** [nblock/ofxstatement-austrian#3]
Hi!

Thanks for the fast reaction an solution of the last issue.

I converted the transactions of the last ~14 months of my Raiffeisen Account and noticed a problem. When I import the file to gnucash, kMyMoney or HomeBank, there are always the same 3 of the 389 transactions missing and a fourth one has no description. I looked at the OFX but couldn't find a reason. In fact there are nearly identical transactions that were imported without a problem.
As the tools (to my knowledge)) all use libOFX for the import I tried ofxdump and found it throws quiet some errors on the file.

Lots of
non SGML character number XXX (mainly 195 and 164 but also 188, 150)
I would guess they refer to german umlauts (ä,ö,ü,ß)?

There is also
LibOFX ERROR: startElement: incoming_data should be empty! You are probably using OpenSP <= 1.3.4.  The folowing data was lost: SEPA Lastschrift Zahlungsempfänger: Deutsche Telekom AG Friedrich Ebert Allee 140 EmpfTTRN>
where the string looks like the beginning of the lost description.

LibOFX ERROR: Tried to close a MEMO but a TRANSACTION is currently open.
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
[..]E: end tag for "STMTTRN" omitted, but its declaration does not permit this
[..] start tag was here

I'm using Ubuntu 14.04.
Can't tell if the problem is in your script, ofxstatement or libOFX. I hope you can help me  with that. :)

**Comment by nblock** [comment]
Waiting for feedback from a private conversation with @mjowe

**Comment by nblock** [comment]
@mjowe is this issue still relevant?

**Comment by nblock** [comment]
Closed due to inactivity.
